# Build matrix
language: cpp
matrix:
  include:
    # Mac OS 10.13 (default)
    - os: osx
      osx_image: xcode9.4
      compiler: clang

    # Mac OS 10.14 (latest)
    - os: osx
      osx_image: xcode11
      compiler: clang
      
# Build library and run tests
script:
  - |
    mkdir build
    cmake -H. -Bbuild -DBUILD_TESTS=ON -DBUILD_UTILS=ON -DCMAKE_BUILD_TYPE=Debug
    cmake --build build
  - ./build/tests/tests
